### ISSUE TITLE
Does this work with all EMS-ESP firmwares?

### ISSUE THREAD

**Issue by Marcus22-try** [bbqkees/ems-esp-domoticz-plugin#1]
Hi,
I've got the hardware up and running. Very fast! It's running 1.8.3 now. Does the Domoticz plugin work with this version? Or do I need to upgrade to 1.9.0? 
Many thanks.

**Comment by bbqkees** [comment]
The plugin works with all versions.
Just make sure you follow the instructions in the readme file.
