### ISSUE TITLE
? boiler temperature

### ISSUE THREAD

**Issue by sq4bja** [bbqkees/ems-esp-domoticz-plugin#11]
After upgrade to b42 i lost boiler temperature. GB072 + R310.
On WWW panel boiler temperature is undefined ℃
On telnet connection it looks like this:

Boiler temperature: ? C
Warm water storage temperature1: ? C
Warm water storage temperature2: 37.6 C

Previously Boiler temperature was the same like WW storage temperature 2.

Tom

**Comment by bbqkees** [comment]
This is an issue with EMS-ESP itself.
Please open an issue on that repository.
