### ISSUE TITLE
Problem With sending thermostat via domoticz

### ISSUE THREAD

**Issue by pierebo** [bbqkees/ems-esp-domoticz-plugin#23]
Hi Kees,
thanks a lot for all the work you did.
i am using your pcb for a while now and everything was working fine until i updated to 2.01
i receive al the settings from my boiler and thermostat, but i can't change the temperature anymore from domoticz.
i did a complete erase  of the wemos with a blank file and started again. no solution. i also updated the files in the plugin directory.
at last i removed the driver from domoticz and installed again.
promblem stays the same.

another question, is it possible to get the shower timer visable in domoticz.

thanks a lot!

**Comment by bbqkees** [comment]
Which thermostat do you have?
Have you set the MQTT topic structure to nested?

Can you show me the payload of the MQTT topics (f.i. with www.mqttexplorer.com).
Should look something like:
![image](https://user-images.githubusercontent.com/10775682/97447991-7101cc80-1930-11eb-83f9-a2e9492abbe0.png)

**Comment by pierebo** [comment]
thats fast! i use a moduline 400 and i did set the MQTT topic structure to nested.
i tried also to change the topic name.

**Comment by pierebo** [comment]
i'm at the office now so i cant check the payload of the MQTT topics now. i wil do this tonight

**Comment by pierebo** [comment]
here i see something strange.
![mqtt](https://user-images.githubusercontent.com/47301498/97453328-e9b75780-1935-11eb-83e3-3a95aabbba37.jpg)

**Comment by bbqkees** [comment]
Could you update to 2.1?
The firmware is here: https://github.com/proddy/EMS-ESP/tree/firmware/firmware
(pick the 8266.bin file).

The plugin is tailored to 2.1. There were so many changes, I'm not sure 2.0.1 would work well.

And then in the MQTT settings set 'Clean session' to on for one reboot. So everything starts fresh on the broker.

**Comment by pierebo** [comment]
that did the trick Thank You verry much!
did you get also the seccond question about the shower timer in domoticz?

**Comment by bbqkees** [comment]
Yes I'll add the shower timer info to the next update.

**Comment by bbqkees** [comment]
The shower timer is now added as a text sensor.

**Comment by pierebo** [comment]
Thanks, i wil try.

Op do 5 nov. 2020 12:53 schreef Kees <notifications@github.com>:

**Comment by pierebo** [comment]
Hi Kees, the shower timer doesnt show up,
I have the latest firmware 2.1.1b1 on the esp and your domoticz plugin. I
see 38 devices from the esp in domoticz but no shower timer.


Op do 5 nov. 2020 13:37 schreef Pierebo <pierebo@gmail.com>:

**Comment by pierebo** [comment]
Its working,  i had to take a shower first...
Thanks for all the work!

Op zo 8 nov. 2020 23:44 schreef Pierebo <pierebo@gmail.com>:
