### ISSUE TITLE
Boiler flame current

### ISSUE THREAD

**Issue by Bartekn86** [bbqkees/ems-esp-domoticz-plugin#24]
1st 
Boiler flame current | General | Current | 26.7 A
its uA (micro Ampere) not ampere :-)
2nd
is it possible to run circulation pump by plan ? using rc310?

**Comment by bbqkees** [comment]
Yes indeed its uA but if I recall correctly Domoticz does not show the values if I load them as 0,0000267A.
And there is no way in Domoticz that I know of to set uA instead of A.

I don't think the boiler circulation pump is a settable parameter.

**Comment by Bartekn86** [comment]
thank you, 
in the rc310 there is an option to turn on the circulation pump once, so it seems possible, but is it really?

**Comment by bbqkees** [comment]
Can you ask this pump question on the EMS-ESP repository?
https://github.com/proddy/EMS-ESP/issues
If the RC310 can turn it on, then EMS-ESP should be able as well but perhaps it needs to be built in.
