### ISSUE TITLE
Missing section boiler_data_ww in plugin -EMS-ESP  v2.1.0

### ISSUE THREAD

**Issue by hetmaanek** [bbqkees/ems-esp-domoticz-plugin#25]
I detected that Domoticz in my configuration not reading all data avaiable directly in EMS-ESP  v2.1.0. interface.
When I looked on MQTT server,missing data are avaiable in section "boiler_data_ww"  but there are not catching by plugin due to missing mention section. 

My configuration:
EMS-ESP  v2.1.0
Domoticz 2020.2
EMS bus Wi-Fi Gateway plugin version 1.2
Boiler GB72, Thermostat Rc300

MQTT Boiler_data frame:
{
  "heatingActive": "on",
  "tapwaterActive": "off",
  "selFlowTemp": 34,
  "selBurnPow": 100,
  "curBurnPow": 25,
  "pumpMod": 100,
  "outdoorTemp": 5.2,
  "curFlowTemp": 38.2,
  "burnGas": "on",
  "flameCurr": 16.2,
  "heatPump": "on",
  "fanWork": "on",
  "ignWork": "off",
  "heatingActivated": "on",
  "heatingTemp": 75,
  "pumpModMax": 100,
  "pumpModMin": 10,
  "pumpDelay": 6,
  "burnMinPeriod": 10,
  "burnMinPower": 0,
  "burnMaxPower": 100,
  "boilHystOn": -6,
  "boilHystOff": 6,
  "UBAuptime": 30388,
  "burnStarts": 413,
  "burnWorkMin": 15341,
  "heatWorkMin": 14362,
  "serviceCode": "-H",
  "serviceCodeNumber": 200
}

boiler_data_ww  frame:
{
  "wWComfort": "Hot",
  "wWSelTemp": 50,
  "wWSetTemp": 10,
  "wWDisinfectionTemp": 70,
  "wWType": "buffer",
  "wWChargeType": "3-way valve",
  "wWCircPump": "off",
  "wWCircPumpMode": "2x3min",
  "wWCirc": "off",
  "wWCurTemp": 48.8,
  "wWCurTemp2": 48.8,
  "wWCurTemp2": 48.7,
  "wWCurFlow": 0,
  "wwStorageTemp2": 48.8,
  "wWActivated": "on",
  "wWOneTime": "off",
  "wWDisinfecting": "off",
  "wWCharging": "off",
  "wWRecharging": "off",
  "wWTempOK": "on",
  "wWActive": "off",
  "wWHeat": "off",
  "wWStarts": 71,
  "wWWorkM": 979
}

**Comment by bbqkees** [comment]
You need to switch to the dev branch where this is solved already or wait a few days until I push it to the main branch.
https://github.com/bbqkees/ems-esp-domoticz-plugin/tree/dev

**Comment by hetmaanek** [comment]
Thanks for info. Dev version working perfect for me.
