### ISSUE TITLE
installing  EMS Plugin domoticz

### ISSUE THREAD

**Issue by ReneUyt** [bbqkees/ems-esp-domoticz-plugin#26]
I am installing the plugin on my PI. running Domoticz, using Mosquitto.
After installation, Domoticz shows the EMS hardware.   As described in the Wiki
But the device list shows 1 EMS item. This item has the type of Switch.
This type I used for my Sonoff modules.
Does anyone knows what I am doing wrong ?

**Comment by ReneUyt** [comment]
I restarted the Gateway. problem solved

**Comment by bbqkees** [comment]
I just updated the main branch of the plugin so you might want to do a git pull in the plugin directory to get the latest version.

**Comment by ReneUyt** [comment]
Beste Kees,
Dank voor de snelle reactie.  Nadat ik de Gateway had herstart werden alle
parameters zichtbaar.
De unit werkt prachtig.  Ik zie dat er heel veel gegevens beschikbaar
komen. Mooi om te zien.
Ook de software van de Gateway zelf is erg mooi en gebruiksvriendelijk
opgebouwd.
mvg
René

Op wo 25 nov. 2020 om 13:42 schreef Kees <notifications@github.com>:
