### ISSUE TITLE
more "devices" in EMS-ESP than in Domoticz

### ISSUE THREAD

**Issue by FWES70** [bbqkees/ems-esp-domoticz-plugin#28]
Hi Kees,

I updated the EMS-ESP to  v2.1.1b6. There are a lot more devices now, most of them I would like to see and monitor in Domoticz as well, but they do not show up (e.g. energy, boiler ext temperature)
I ulpoaded the last plugin, hoping it would change.

any plans to update? Can I help in any way?

**Comment by bbqkees** [comment]
Can you make a list of which additional parameters you need and which you would also like to see?

A Domoticz python plugin is limited to only 256 devices. I'm already using a lot of them so additional space is limited.
But it's a bit of 'first come first served' so the first persons to drop useful parameters here will have their wishes (mostly) granted.

**Comment by FWES70** [comment]
[devices to be added to Domoticz.xlsx](https://github.com/bbqkees/ems-esp-domoticz-plugin/files/5637486/devices.to.be.added.to.Domoticz.xlsx)

this is the list of parameters I would like to see in Domoticz.
would it be an idea to make a separate plugin for heatpumps? I guess the owners of a gas boiler are not so interested in the heatpump parameters. But I have no clue how much work it is, so I leave it to you...

**Comment by bbqkees** [comment]
Can you post a complete payload of the topics in your system?
I would like to acquire some examples as i don't have a heat pump myself.
You can use f.i. https://mqtt-explorer.com/

**Comment by FWES70** [comment]
Is this what you mean?
Boiler_data
{"heatingActive":"off","tapwaterActive":"off","selFlowTemp":32,"selBurnPow":0,"curBurnPow":0,"pumpMod":0,"pumpMod2":0,"outdoorTemp":7.7,"curFlowTemp":31.2,"exhaustTemp":0,"burnGas":"off","flameCurr":0,"heatPump":"on","fanWork":"off","ignWork":"off","heatingActivated":"on","heatingTemp":85,"burnMinPeriod":10,"burnMinPower":0,"burnMaxPower":100,"boilHystOn":-6,"boilHystOff":6,"burnStarts":0,"burnWorkMin":0,"heatWorkMin":0,"UBAuptime":791921,"serviceCode":" 0H","serviceCodeNumber":203,"upTimeControl":282855,"upTimeCompHeating":239703,"upTimeCompCooling":0,"upTimeCompWw":43151,"heatingStarts":1323,"coolingStarts":0,"wWStarts2":569,"nrgConsTotal":4408,"auxElecHeatNrgConsTotal":537,"auxElecHeatNrgConsHeating":0,"auxElecHeatNrgConsDHW":537,"nrgConsCompTotal":3871,"nrgConsCompHeating":2619,"nrgConsCompWw":1249,"nrgConsCompCooling":0,"nrgSuppTotal":14872,"nrgSuppHeating":11088,"nrgSuppWw":3779,"nrgSuppCooling":0}

Heatpump_data
{"airHumidity":21.5,"dewTemperature":7}

Boiler_data_ww
{"wWSelTemp":60,"wWSetTemp":57,"wWDisinfectionTemp":65,"wWCircPump":"off","wWCircPumpMode":"3x3min","wWCirc":"off","wWCurTemp":48.8,"wWCurTemp2":47.6,"wWActivated":"on","wWOneTime":"off","wWDisinfecting":"off","wWCharging":"off","wWRecharging":"off","wWTempOK":"off","wWHeat":"off"}

Thermostat_data
{"time":"10:11:38 04/12/2020","dampedtemp":7.2,"minexttemp":-10,"building":"medium","wwmode":"high","wwextra1":0,"wwcircmode":"on","hc1":{"seltemp":19,"currtemp":17,"comforttemp":21,"ecotemp":15,"manualtemp":19,"nofrosttemp":5,"heatingtype":3,"targetflowtemp":32,"offsettemp":0,"designtemp":40,"roominfluence":1,"minflowtemp":25,"maxflowtemp":48,"summertemp":0,"summermode":"summer","mode":"manual","modetype":"comfort"}}

**Comment by bbqkees** [comment]
Ok thats quite some new ones indeed.
I'll add a number of them in the next update.

**Comment by bbqkees** [comment]
I added lots of parameters in the dev branch.
Can you try them out?

**Comment by FWES70** [comment]
I gave it a try. looks like the devices do not load anymore. after pressing a few times on "all devices" (alle apparaten), it loads randomly a few more (14 out of the >100 that I had before). I only see 1 of my sonoffs in the list for example.
after I press the refresh button all devices disapear.

**Comment by bbqkees** [comment]
Ok. I believe this is the same problem as we experienced with the old plugin for 1.9.5.
As soons as you reach a certain number of devices (even below the allowed 256), it all falls apart.

I'll create another plugin branch with a selector or something. Then you can create two instances of the same plugin but with only half of the parameters each. Let's see if that solves it.

**Comment by FWES70** [comment]
it might be a problem with Domoticz: I changed back to the old plugin, but the problem persisted. re-insalled Domoticz, but it is still the same now.

**Comment by bbqkees** [comment]
Yes it's an annoying problem.
You have to disable the plugin and remove all its devices otherwise the empty device list will persist.

**Comment by FWES70** [comment]
OK, I'll try that first, otherwise a complete re-install of Domoticz, without putting back the DB (result will probably be the same)

**Comment by Bartekn86** [comment]
could you add function to start circulation pump in rc310 please ?

**Comment by bbqkees** [comment]
@Bartekn86 I've added it the the dev branch. Make a database backup before updating, if could be the plugin creates too many devices and that will mess up the device list in Domoticz.

**Comment by Bartekn86** [comment]
thank you, 
could you tell what is the name of parameter/button etc. to start running pump ?
or how should be configured  rc310 to run pump "from the finger" - manual
b.

**Comment by bbqkees** [comment]
The empte device list problem should be solved. See #33
