### ISSUE TITLE
Devices doesn’t update

### ISSUE THREAD

**Issue by edwin123456** [bbqkees/ems-esp-domoticz-plugin#29]
In the Domoticz plugin the devices dont get updated , in telnet they do 
Is there a solution?

**Comment by bbqkees** [comment]
Can you be a bit more specific?

Is this is new setup or did it work before?
Did you set the correct IP address in Domoticz?
Is the topic structure set to nested in the MQTT settings?
Can you see all topics with www.mqtt-explorer.com?

**Comment by edwin123456** [comment]
Hoi kees,
Het heeft altijd gewerkt,
Als ik Domoticz opnieuw start dan update hij 1 keer en daar blijft het dan bij, in het domoticz log staat : EMS bus Wi-Fi Gateway) onMessage called with: PINGRESP

Via telnet werkt alles goed. 
Als je meer wilt weten hoor ik het graag.
Bedankt voor je reactie. 
Mvg 
Edwin

**Comment by bbqkees** [comment]
Ok. Is er iets veranderd voordat ie het niet meer deed?
Als het in Telnet werkt, dan werkt iig de Gateway nog. Echter zijn er daarna diverse punten waar alles kan stranden.
Kun je de machine waar Domoticz op draait een keer opnieuw opstarten
Kun je met www.mqtt-explorer.com zien dat topics daadwerkelijk gepubliceerd worden?

**Comment by edwin123456** [comment]
Ik heb met een ander programma mqtt bekeken zie hier:

{"heatingActive":"on","tapwaterActive":"off","selFlowTemp":50,"selBurnPow":46,"curBurnPow":23,"pumpMod":30,"curFlowTemp":55,"retTemp":44.7,"switchTemp":0,"sysPress":2.3,"boilTemp":54.8,"burnGas":"on","flameCurr":26.1,"heatPump":"on","fanWork":"on","ignWork":"off","heatingActivated":"on","heatingTemp":75,"pumpModMax":30,"pumpModMin":30,"pumpDelay":5,"burnMinPeriod":10,"burnMinPower":0,"burnMaxPower":46,"boilHystOn":-6,"boilHystOff":6,"burnStarts":12228,"burnWorkMin":51052,"heatWorkMin":41815,"UBAuptime":639798,"serviceCode":"-H","serviceCodeNumber":200,"lastCode":"2E(207) 05.12.2020 08:48","maintenanceMessage":" "}

Ik zal morgen de computer een keer opnieuw opstarten,
Alvast bedankt weer.

**Comment by edwin123456** [comment]
Hoi Kees,
Ik heb de raspberry pi opnieuw gestart, maar het blijft het zelfde ,waardes worden 1 keer geupdate daarna niet meer.
Als ik naar 
ems-esp/boiler_data kijk word alles geupdate
Maar bij 
home/ems-esp/boiler_data
Gebeurd dat niet , die waardes staan in domoticz

Alvast bedankt voor je hulp
Mvg
Edwin

**Comment by bbqkees** [comment]
Je moet home/ eraf halen in de plugin instellingen. Dan werkt het weer.
Waarschijnlijk heb je een keer een firmware update gedaan maar de Gateway niet herstart en is die de oude topic structuur blijven sturen.

**Comment by edwin123456** [comment]
Ja, 
Dat is het. 
Stom dat ik het zelf niet zag. 
Super bedankt voor je hulp!!
Mvg
Edwin

**Comment by bbqkees** [comment]
Je gaf zelf het antwoord eigenlijk al. Had alleen even een klein zetje nodig. :-)

Het werkt weer dus ik sluit deze issue.
