### ISSUE TITLE
New development branch for testing empty device list problem

### ISSUE THREAD

**Issue by bbqkees** [bbqkees/ems-esp-domoticz-plugin#33]
I have created a new version of the plugin that should prevent the issue with the empty device list in Domoticz:
https://github.com/bbqkees/ems-esp-domoticz-plugin/tree/dev-multi2

If you use this version, it's best to start over again.
So delete all devices from the old version and start fresh.

For each EMS device you have (so boiler, thermostat, etc) you have to create a separate instance of the plugin.
So you install it once, but you add a new hardware of the type EMS gateway in the hardware listr in Domoticz.

**Comment by FWES70** [comment]
bbqkees, it seems not to work for the older version of the gateway (ESP8266 based), correct? it loads only 4 devices per hardware so far. I updated the EMS-ESP to v2.2.2.

**Comment by FWES70** [comment]
[plugin v2.xlsx](https://github.com/bbqkees/ems-esp-domoticz-plugin/files/6501286/plugin.v2.xlsx)

Hi Kees, I made a download of the MQTT messages and also added the log from Domoticz, all sorted  in Excel. maybe this helps.

**Comment by bbqkees** [comment]
@FWES70 Now I see that in EMS-ESP 2.2.2 the MQTT parameters have not changed to all lower case, this is only in EMS-ESP32 V3.....

I think if I just convert all names to lower case by default before processing them it should work for V2.2 as well.

**Comment by bbqkees** [comment]
@FWES70 Can you update the plugin and check if it works for V2.2 now?

**Comment by FWES70** [comment]
@bbqkees I tried it, but Domoticz becomes unstable (this was also the case with the first one). in the meantime I worked on the previous version and made it work, all devices appear in Domoticz now (mainly upper-case and correct naming according to the EMS output).  
how can I share that with you?

**Comment by bbqkees** [comment]
Please try out the new Autodiscovery feature of Domoticz instead of this plugin.
See https://bbqkees-electronics.nl/wiki/gateway/domoticz-configuration.html

(You can run them side by side with the existing plugin for a while).
