### ISSUE TITLE
EMS-ESP 3.1.1 problem

### ISSUE THREAD

**Issue by sq4bja** [bbqkees/ems-esp-domoticz-plugin#34]
After updating EMS-ESP to version 3.1.1, the plugin does not update the circuit temperatures, the boiler devices are not updated. The only thing that is updated is the temperature of the dallas thermometers.

**Comment by bbqkees** [comment]
Some time ago the names of a lot of parameters in the MQTT payload have changed (all lowercase now).
I guess you now updated to a version which has the newer names.

I created an update in another branch, which already took this into account:
https://github.com/bbqkees/ems-esp-domoticz-plugin/blob/dev-multi2

**Comment by sq4bja** [comment]
Thanks, it helps. 
But the new plugin adds new devices. You cannot change their name to a more friendly one, because the plugin will then create another device with the default name.

UPDATE: Strange things happen .... After another Domoticz reboot, old devices started updating.
