### ISSUE TITLE
Boiler System Pressure not updating

### ISSUE THREAD

**Issue by FireWizard52** [bbqkees/ems-esp-domoticz-plugin#35]
Hello,

Since April 23  (approx) the System Pressure is not updating anymore.
This could be caused by updating to 2.2.1 and later to 2.2.2., but I'm not sure.

In the Web interface of EMS-ESP the value is correct and also the MQTT message is correct.
Checked with MQTT Explorer and Node Red.

I also checked the source code but did not find anything that could cause the missing update.

I deleted the specific sensor "Boiler System Pressure" (not de whole hardware plugin) and expected that this sensor would be recreated, if I would enable hardware and restart the system.
It did not happen.

For now I created a workaround with a virtual sensor and Node Red.
That is okay.

Any ideas, hints, suggestions?

**Comment by bbqkees** [comment]
Please try out the new Autodiscovery feature of Domoticz instead of this plugin.
See https://bbqkees-electronics.nl/wiki/gateway/domoticz-configuration.html

(You can run them side by side with the existing plugin for a while).
