### ISSUE TITLE
more "devices" in EMS-ESP than in Domoticz

### ISSUE THREAD

**Issue by Thom1984** [bbqkees/ems-esp-domoticz-plugin#41]
I have more devices from my EMS-ESP then in Domoticz. I would like to have 'heatingPumpMod' in Domoticz

MQTT explorer

Boiler Data
{"heatingActive":"on","tapwaterActive":"off","selFlowTemp":65,"selBurnPow":6,"curBurnPow":23,"heatingPumpMod":30,"curFlowTemp":31.5,"retTemp":25.5,"switchTemp":0,"sysPress":2.2,"boilTemp":32,"burnGas":"on","flameCurr":16.7,"heatingPump":"on","fanWork":"on","ignWork":"off","heatingActivated":"on","heatingTemp":65,"pumpModMax":65,"pumpModMin":30,"pumpDelay":10,"burnMinPeriod":10,"burnMinPower":0,"burnMaxPower":34,"boilHystOn":-6,"boilHystOff":6,"burnStarts":49222,"burnWorkMin":539930,"heatWorkMin":482359,"UBAuptime":3034428,"serviceCode":"-H","serviceCodeNumber":200,"lastCode":"6L(229) 01.10.2021 17:40","maintenanceMessage":"-","maintenance":"off"}

Boilter data WW
{"wWComfort":"Eco","wWSelTemp":60,"wWSetTemp":62,"wWDisinfectionTemp":70,"wWType":"flow","wWChargeType":"3-way valve","wWCircPump":"off","wWCircPumpMode":"0x3min","wWCirc":"off","wWCurTemp":27,"wWCurFlow":0,"wWStorageTemp1":27,"wWActivated":"on","wWOneTime":"off","wWDisinfecting":"off","wWCharging":"off","wWRecharging":"off","wWTempOK":"on","wWActive":"off","wWHeat":"off","wWStarts":19536,"wWMaxPower":100,"wWWorkM":57571}

**Comment by bbqkees** [comment]
Please try out the new Autodiscovery feature of Domoticz instead of this plugin.
See https://bbqkees-electronics.nl/wiki/gateway/domoticz-configuration.html

(You can run them side by side with the existing plugin for a while).
