### ISSUE TITLE
Heating inndicator not working

### ISSUE THREAD

**Issue by sq4bja** [bbqkees/ems-esp-domoticz-plugin#42]
Hi,
After the heating season started, I noticed that the heating light did not change state. EMS-ESP in the newest version for ESP32, like plugin for domoticz (dev-multi2). In the EMS-ESP itself, the heating states are displayed correctly. The error occurs in the plugin for domoticz.
In my configuration, the heating indicator has the ID: 001D0048 unit 72.
Below is the current status of the Boiler branch MQTT:

`{"id":123,"heatingactive":"on","tapwateractive":"off","selflowtemp":29,"selburnpow":57,"heatingpumpmod":68,"outdoortemp":8.7,"curflowtemp":26.8,"burngas":"off","flamecurr":0,"heatingpump":"on","fanwork":"off","ignwork":"off","heatingactivated":"on","heatingtemp":70,"pumpmodmax":100,"pumpmodmin":10,"pumpdelay":10,"burnminperiod":20,"burnminpower":0,"burnmaxpower":57,"boilhyston":-6,"boilhystoff":6,"curburnpow":0,"burnstarts":7967,"burnworkmin":467942,"heatworkmin":366511,"ubauptime":1949279,"lastcode":"6A(227) 16.09.2020 16:21","servicecode":"0Y","servicecodenumber":204,"maintenance":"off","maintenancetime":6000,"maintenancedate":"01.01.2009"}`

Tom

**Comment by sq4bja** [comment]
Adding this in boiler_data topic helps. I thing, old topic heating_active doesn`t work in new ems-esp firmware.
```
################
                if "heatingactive" in payload:
                    switchstate=payload["heatingactive"]
                    if 72 not in Devices:
                        Domoticz.Debug("Create on/off switch (heating active)")
                        Domoticz.Device(Name="Heating active", Unit=72, Type=244, Subtype=73, Switchtype=0).Create()
                    updateDevice(72, 244, 73, switchstate)
###############

```

**Comment by bbqkees** [comment]
Please try out the new Autodiscovery feature of Domoticz instead of this plugin.
See https://bbqkees-electronics.nl/wiki/gateway/domoticz-configuration.html

(You can run them side by side with the existing plugin for a while).
