### ISSUE TITLE
Error setting CV Thermostat Setpoint

### ISSUE THREAD

**Issue by sciurius** [bbqkees/ems-esp-domoticz-plugin#45]
Latest version, dev-multi2 branch.

When I try to set the setpoint, the plugin gets an error:
````
domoticz[26236]: 2021-12-15 13:24:37.061  Error: Thermostat: (Thermostat) 'onCommand' failed 'TypeError':'onCommand() missing 1 required positional argument: 'hue''.
domoticz[26236]: 2021-12-15 13:24:37.061  Error: Thermostat: (Thermostat) ----> Line 1110 in '/opt/domoticz/plugins/ems-esp-domoticz-plugin/plugin.py', function onCommand
````

**Comment by bbqkees** [comment]
Please try out the new Autodiscovery feature of Domoticz instead of this plugin.
See https://bbqkees-electronics.nl/wiki/gateway/domoticz-configuration.html

(You can run them side by side for a while).

**Comment by sciurius** [comment]
I'll wait until the Autodiscovery feature is released.
