### ISSUE TITLE
RC35 thermostat (moduline 400) set commands not working

### ISSUE THREAD

**Issue by th3sniper86** [bbqkees/ems-esp-domoticz-plugin#7]
Changing mode (auto/manual...) and setting temperature not working anymore. 
ESP firmware: 1.9.4 and 1.9.5b28 
Plugin: master and dev 

Has worked in the past (do'n no wich versions).

**Comment by bbqkees** [comment]
The MQTT topics were changes once again.
Can you try the dev?
I made some changes.

**Comment by th3sniper86** [comment]
Did a quick test. Working again! Thanks :)

**Comment by bbqkees** [comment]
Ok great I'll change it for the master branch as well.
