### ISSUE TITLE
Update device state

### ISSUE THREAD

**Issue by sq4bja** [bbqkees/ems-esp-domoticz-plugin#9]
Is it possible to change the way devices are updated? Currently, every telegram updates the devices in domoticz. Even if the change of state did not occur. It would be good to verify the current state of the device in Domoticz and apply the update if there is a difference. After this modification, you can create DZVents scripts that will run only after changing the status of the device, not every 10 seconds. It saves a lot of CPU performance and the size of the database of all updated devices.
Tom

**Comment by bbqkees** [comment]
Yes you are right the current plugin bombards Domoticz with status updates.
Its still on the todo list.

**Comment by bbqkees** [comment]
With every new telegram the current values are checked for most devices, however I was comparing them in the wrong way so even when the value was the same it still updates.
Its something I'll change in a next update somewhere next month.

**Comment by bbqkees** [comment]
I'm currently simplifying the plugin and already testing a fix for the updates.

**Comment by bbqkees** [comment]
Can you try the dev?
All devices should only be updated when the value has actually changed.

**Comment by sq4bja** [comment]
Ok, it works. But i don't know what will happen if the device is not updated for a long time. Will it not appear in red like offline?

**Comment by bbqkees** [comment]
Yes after a certain amount of time the sensors time out.
I'll see if I can add a check to the sensor updates when its after a certain amount of time it will update the sensor even if its still the same value.
maybe i can also add a parameter so you can configure the timeout-check yourself.
